const tasks = [
  { kind: 'spotify trivia', difficult: true, type: 'spotify', track: '4cHLWRM6G50xUOYoichYZ9', question: 'Who\'s the author of this song?', answer: 'Fulton Lee', options: ['Two Feet', 'Fulton Lee', 'Supermassive', 'Tristam'] },
  { kind: 'spotify trivia', difficult: true, type: 'spotify', track: '5K43AHQPTJTqlyRZ3uBGKz', question: 'Who\'s the author of this song?', answer: 'Saint Motel', options: ['Saint Motel', 'City Wolf', 'Tobu', 'The Happy Fits'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '4wxTn03zuXvkQwNvI6oHyF', question: 'What\'s the name of this song?', answer: 'Preach', options: ['Preach', 'Lonely', 'Teach', 'Baby Baby'] },
  { kind: 'spotify trivia', difficult: true, type: 'spotify', track: '1bn6dqeM5Sle3rYsZXPvdx', question: 'Who\'s the author of this song?', answer: 'Jake Daniels', options: ['Jake Daniels', 'Stellar', 'Supermassive', 'NEFFEX'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '2uWTSzExDgzISj7pL8C9FH', question: 'What\'s the name of this song?', answer: 'Obey the Groove', options: ['Obey the Groove', 'Critical Hit', 'Supernatural', 'Together on Mars'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '5fVqumMSkKG5hPaV6vqWLR', question: 'What\'s the name of this song?', answer: 'Chasing Tomorrow', options: ['Chasing Tomorrow', 'Folowing the Sun', 'My Mind', 'La La La La'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '3XREkzDHsWdBL5tybyCDBH', question: 'What\'s the name of this song?', answer: 'SloMo', options: ['SloMo', 'Novia', 'me duele el culo', 'Adelante'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '0ihBqor5qruOuBSoXN9xVY', question: 'What\'s the name of this song?', answer: 'Reason', options: ['Reason', 'Novia', 'So Young', 'Rockstar'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '2sFbdDiEDpyCdP5nUCuGBm', question: 'What\'s the name of this song?', answer: 'Following the Sun', options: ['Following the Sun', 'Chasing Tomorrow', 'Light walk', 'The Road'] },
  { kind: 'spotify trivia', difficult: true, type: 'spotify', track: '1nO9qYFTq5ZkiiXnaXbBEH', question: 'What\'s the name of this song?', answer: 'One By One', options: ['One By One', 'Take It From Me', 'Be My Fire', 'Slow Dance'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '4Bdc2PsSlWoLtvtSMJ5SRG', question: 'What\'s the name of this song?', answer: 'So So Young', options: ['So So Young', 'Take It From Me', 'Be My Fire', 'Trip to LA'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '1dX6oGAG5PaexuPj29PsYd', question: 'What\'s the name of this song?', answer: 'I Can\'t Go on Without You', options: ['I Can\'t Go on Without You', 'Without You', 'Way Down We Go', 'Taylor Swift'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '0zPQx8X0MqfilG0dZIRXkN', question: 'What\'s the name of this song?', answer: 'Problems', options: ['Problems', 'Pro', 'Pain', 'Stalker'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '3EetDRais2bTue3poVvXYj', question: 'What\'s the name of this song?', answer: 'Good Man', options: ['Good Man', 'Woman\'s Man', 'Man', 'Life I\'m Living'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '3GN4qe6CrarjGTZU2DdpEe', question: 'What\'s the name of this song?', answer: 'Liar', options: ['Red Dress', 'Princess', 'Liar', 'Problems'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '3GfOAdcoc3X5GPiiXmpBjK', question: 'What\'s the name of this song?', answer: 'Song 2', options: ['Song 2', 'WooHoo', 'Jumbo', 'I need you'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '0Tr5G2mE56eLUGvCaXRM8I', question: 'Who\'s the author of this song?', answer: 'Kaleo', options: ['Kaleo', 'NEFFEX', 'Stellar', 'Two Feet'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '4cOdK2wGLETKBW3PvgPWqT', question: 'What\'s the name of this song?', answer: 'Never Gonna Give You Up', options: ['Never Gonna Give You Up', 'Never Gonna Say Goodbye', 'Never Gonna Let You Down', 'Never Gonna Tell A Lie'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '6gGBL1uMBcNUOzSYfKreID', question: 'Who\'s the author of this song?', answer: 'Two Feet', options: ['Kaleo', 'NEFFEX', 'The Weeknd', 'Two Feet'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '39LLxExYz6ewLAcYrzQQyP', question: 'Who\'s the author of this song?', answer: 'Dua Lipa', options: ['Dua Lipa', 'Rihanna', 'Shakira', 'Taylor Swift'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '15j4ae8LscKv31jxLHCp6V', question: 'Who\'s the author of this song?', answer: 'Fox Stevenson', options: ['Harry Styles', 'Fox Stevenson', 'Ofenbach', 'The Weeknd'] },
  { kind: 'spotify trivia', difficult: true, type: 'spotify', track: '4Dvkj6JhhA12EX05fT7y2e', question: 'Who\'s the author of this song?', answer: 'Harry Styles', options: ['Harry Styles', 'Fox Stevenson', 'Ofenbach', 'The Weeknd'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '1DeGDoa5UvKyp9ShMz8A5I', question: 'What\'s the name of this song?', answer: 'Sweep The Leg', options: ['Sweep The Leg', 'Critical Hit', 'Obey The Groove', 'Dojo'] },
  { kind: 'spotify trivia', difficult: true, type: 'spotify', track: '3n69hLUdIsSa1WlRmjMZlW', question: 'Who\'s the author of this song?', answer: 'alt-J', options: ['alt-J', 'ctrl+alt+del', 'alt+F4', 'shift+alt'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '5idsEzxjeekla54j0jHYUE', question: 'What\'s the name of this song?', answer: 'Good In Bed', options: ['Good In Bed', 'Bed Bed Bed', 'Bad Bad Bad', 'Rest in Bed'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '0lwUIYJfWGB8qUEAJtYfb6', question: 'What\'s the name of this song?', answer: 'Broken Bones', options: ['Broken Bones', 'Devil Got \'em', 'All the Pretty Girls', 'Save Yourself'] },
  { kind: 'spotify trivia', difficult: true, type: 'spotify', track: '5K2YU3ENuytMsx9bfJOFrw', question: 'What\'s the name of this song?', answer: 'Don\'t Matter', options: ['Don\'t Matter', 'Broken Bones', 'Confidence', 'Need Sleep'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '4r05ev9hIFnjWUkzJGMu46', question: 'What\'s the name of this song?', answer: 'Flatline', options: ['Flatline', 'Quicklime', 'Big Fan', 'Love is a Bitch'] },
  { kind: 'spotify trivia', difficult: true, type: 'spotify', track: '6nHHDXbynszHt3aFR7Ujvz', question: 'What\'s the name of this song?', answer: 'All Hallows', options: ['All Hallows', 'Guilty Pleasures', 'Halloween', 'Cursed Night'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '4gpTRoSrTarhs4HdQzrS11', question: 'Who\'s the author of this song?', answer: 'Ot Vinta', options: ['Ot Vinta', 'Druga Rika', 'Antytila', 'adm:t'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '1bloF1LHgUVvPJLxrzxgu7', question: 'What\'s the name of this song?', answer: 'Automobile', options: ['Automobile', 'Road', 'Roder', 'Gringo'] },
  { kind: 'spotify trivia', difficult: true, type: 'spotify', track: '1vvNmPOiUuyCbgWmtc6yfm', question: 'What\'s the name of this song?', answer: 'My Way', options: ['My Way', 'Why Wait', 'About You', 'My Move'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '4Ikv8t2Ui1wSSbqKdo4c1t', question: 'Who\'s the author of this song?', answer: 'Roman Lewis', options: ['Roman Lewis', 'Teddy Hyde', 'Confetti', 'Jon Fratelli'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '3dPQuX8Gs42Y7b454ybpMR', question: 'Who\'s the author of this song?', answer: 'The White Stripes', options: ['The White Stripes', 'Kaleo', 'The Killers', 'Nirvana'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '6RB9YvNyP0RZfCUcMtZELH', question: 'What\'s the name of this song?', answer: 'Freedom', options: ['Freedom', 'Get Lucky', 'Happy', 'Blurred Lines'] },
  { kind: 'spotify trivia', difficult: true, type: 'spotify', track: '2KklXplRtxMsBYo474Es0w', question: 'What\'s the name of this song?', answer: 'Be Mine', options: ['Be Mine', 'Rock It', 'Around the Fire', 'Summer Party'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '7qiZfU4dY1lWllzX7mPBI3', question: 'Who\'s the author of this song?', answer: 'Ed Sheeran', options: ['Ed Sheeran', 'Justin Bieber', 'Bruno Mars', 'Sam Smith'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '7hCNBVRhHzcsRAv0TQnOzq', question: 'Who\'s the author of this song?', answer: 'Bruno Mars', options: ['Ed Sheeran', 'Justin Timberlake', 'Bruno Mars', 'Chris Brown'] },
  { kind: 'spotify trivia', difficult: true, type: 'spotify', track: '6nek1Nin9q48AVZcWs9e9D', question: 'What\'s the name of this song?', answer: 'Paradise', options: ['Paradise', 'Yellow', 'Fix You', 'Clocks'] },
  { kind: 'spotify trivia', difficult: true, type: 'spotify', track: '6RUKPb4LETWmmr3iAEQktW', question: 'What\'s the name of this song?', answer: 'Something Just Like This', options: ['Something Just Like This', 'Paris', 'Closer', 'Don\'t Let Me Down'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '1mea3bSkSGXuIRvnydlB5b', question: 'Who\'s the author of this song?', answer: 'Coldplay', options: ['Coldplay', 'U2', 'Imagine Dragons', 'The Rolling Stones'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '32OlwWuMpZ6b0aN2RZOeMS', question: 'What\'s the name of this song?', answer: 'Uptown Funk', options: ['Uptown Funk', 'Treasure', 'Happy', 'Can\'t Stop the Feeling!'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '34xGLuxM0rkxhCVyMSqwJO', question: 'What\'s the name of this song?', answer: 'Stolen Dance', options: ['Stolen Dance', 'Blurred Lines', 'Breezeblocks', 'Riptide'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '4xigPf2sigSPmuFH3qCelB', question: 'What\'s the name of this song?', answer: 'Genius', options: ['Genius', 'Hello', 'Diamonds', 'Last Friday Night'] },
  { kind: 'spotify trivia', difficult: true, type: 'spotify', track: '6Sq7ltF9Qa7SNFBsV5Cogx', question: 'What\'s the name of this song?', answer: 'Me Porto Bonito', options: ['Me Porto Bonito', 'Hasta Luego', 'La Modelo', 'X'] },
  { kind: 'spotify trivia', difficult: true, type: 'spotify', track: '6Y46tOTRhkBamosyuWa6YX', question: 'What\'s the name of this song?', answer: 'La Fama', options: ['La Fama', 'Waka Waka', 'Bailando', 'Corazón Partío'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '6bNB5gxFX6Q87DbQWb8OWZ', question: 'Who\'s the author of this song?', answer: 'Shakira', options: ['Shakira', 'Jennifer Lopez', 'Selena Gomez', 'Rihanna'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '53tfEupEzQRtVFOeZvk7xq', question: 'Who\'s the author of this song?', answer: 'Rosalía', options: ['Rosalía', 'La Niña de los Peines', 'Kali Uchis', 'Natalia Lafourcade'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '6ZOcbKub95XSDESsKKuH41', question: 'What\'s the name of this song?', answer: 'Desesperados', options: ['Me Enamore', 'Intoxicados', 'Desesperados', 'Los Desperados'] },
  { kind: 'spotify trivia', difficult: true, type: 'spotify', track: '0qOnSQQF0yzuPWsXrQ9paz', question: 'What\'s the name of this song?', answer: 'My Heart\'s a Stereo', options: ['My Heart\'s a Stereo', 'I\'m Your Stereo', 'Stereo Love', 'Stereo Heart'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '78lgmZwycJ3nzsdgmPPGNx', question: 'Who\'s the author of this song?', answer: 'Led Zeppelin', options: ['The Rolling Stones', 'Led Zeppelin', 'Pink Floyd', 'The Who'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '4mn2kNTqiGLwaUR8JdhJ1l', question: 'Who\'s the author of this song?', answer: 'The Animals', options: ['The Beatles', 'The Rolling Stones', 'The Animals', 'Led Zeppelin'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '1hwJKpe0BPUsq6UUrwBWTw', question: 'Who\'s the author of this song?', answer: 'Green Day', options: ['Green Day', 'Blink-182', 'Fall Out Boy', 'Foo Fighters'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '1pjvlYOMIg1NhGQbM6iwrY', question: 'What\'s the name of this song?', answer: 'Light it Up Remix', options: ['Light it Up Remix', 'Lean On', 'Get Lucky', 'Rockabye'] },
  { kind: 'spotify trivia', difficult: true, type: 'spotify', track: '3aTb5EUBOlNDSEcaTFI7Jj', question: 'What\'s the name of this song?', answer: 'Bodyrock', options: ['Porcelain', 'Natural Blues', 'Go', 'Bodyrock'] },
  { kind: 'spotify trivia', difficult: true, type: 'spotify', track: '1ChulFMnwxoD74Me8eX2TU', question: 'Who\'s the author of this song?', answer: 'Dead Or Alive', options: ['Dead Or Alive', 'Pet Shop Boys', 'Duran Duran', 'Culture Club'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '7CvOnbFdnIoXMQ4eFCo5lB', question: 'What\'s the name of this song?', answer: 'Around the World', options: ['Across the Globe', 'Around the World', 'La La La', 'Travelling the World'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '1TfqLAPs4K3s2rJMoCokcS', question: 'What\'s the name of this song?', answer: 'Sweet Dreams', options: ['Sweet Dreams', 'Dream On', 'Dreamscape', 'Dreams'] },
  { kind: 'spotify trivia', difficult: true, type: 'spotify', track: '3LNgoqv3AboDUhnuWrrzSF', question: 'Who\'s the author of this song?', answer: 'Liar, Liar', options: ['Liar, Liar', 'Firestarters', 'Truth Hurts', 'False Lies'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '4mmJ9f97Yr1E7YuEu92ir2', question: 'What\'s the name of this song?', answer: 'Intoxicated', options: ['High on You', 'Intoxicated', 'Drunk in Love', 'Dance Fever'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '27SdWb2rFzO6GWiYDBTD9j', question: 'What\'s the name of this song?', answer: 'Cheap Thrills', options: ['Cheap Thrills', 'Move Your Body', 'Big Girls Don\'t Cry', 'Have fun tonight'] },
  { kind: 'spotify trivia', difficult: true, type: 'spotify', track: '1MJjw68l1Djgbq04BRggsn', question: 'What\'s the name of this song?', answer: 'In The Heat Of A Disco', options: ['In The Heat Of A Disco', 'Dancing Queen', 'Disco Fever', 'Boogie Nights'] },
  { kind: 'spotify trivia', difficult: true, type: 'spotify', track: '7wMq5n8mYSKlQIGECKUgTX', question: 'Who\'s the author of this song?', answer: 'The Script', options: ['Coldplay', 'Imagine Dragons', 'The Script', 'OneRepublic'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '5gCNf9wMVrYuM2fvfgLTlF', question: 'What\'s the name of this song?', answer: 'La Combi Versace', options: ['La Combi Versace', 'La Combi Louis Vuitton', 'La Combi Gucci', 'La Combi Chanel'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '0fADaWdT3obxk7zvHS18VY', question: 'What\'s the name of this song?', answer: 'PANTIES Y BRASIERES', options: ['PANTIES Y BRASIERES', 'TATUAJES Y RECUERDOS', 'ROPA INTERIOR Y CHAQUETAS', 'MEDIAS Y ZAPATOS'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '5K9VzfSr7L34rMMJxe8ndg', question: 'What\'s the name of this song?', answer: 'En Bajita', options: ['En Bajita', 'En Alta', 'En Mediana', 'En Gigante'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '78QcVmzxS0wIwuC2rpAauI', question: 'Who\'s the author of this song?', answer: 'Rauw Alejandro', options: ['Rauw Alejandro', 'Bad Bunny', 'J Balvin', 'Daddy Yankee'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '75rqqKvzJCGv2oq9C4yFDt', question: 'What\'s the name of this song?', answer: 'PROMESA', options: ['PROMESA', 'ESPERANZA', 'COMPROMISO', 'SUEÑO'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '3k3NWokhRRkEPhCzPmV8TW', question: 'What\'s the name of this song?', answer: 'Ojitos Lindos', options: ['Ojitos Lindos', 'Ojitos Bonitos', 'Ojitos Preciosos', 'Ojitos Hermosos'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '6Xj014IHwbLVjiVT6H89on', question: 'Who\'s the author of this song?', answer: 'Kenia OS', options: ['Kenia OS', 'Rosalía', 'Malucci', 'Paloma Mami'] },
  { kind: 'spotify trivia', difficult: true, type: 'spotify', track: '7KBcTRmmuKu8kSRsP8HGyt', question: 'Who\'s the author of this song?', answer: 'Malucci', options: ['Malucci', 'Rosalía', 'Paloma Mami', 'Kenia OS'] },
  { kind: 'spotify trivia', difficult: true, type: 'spotify', track: '2SiAcexM2p1yX6joESbehd', question: 'What\'s the name of this song?', answer: 'Lie Like You Love Me', options: ['Lie Like You Love Me', 'Say It Like You Mean It', 'Pretend You Love Me', 'Fake It Till You Make It'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '6Rpbzk2LC8xWZI93RyodAq', question: 'What\'s the name of this song?', answer: 'Hey Mor', options: ['Hey Mor', 'Hey Baby', 'Hey Ma', 'Hey Girl'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '5jW3rF4URMdK7tO2xjS5EI', question: 'What\'s the name of this song?', answer: 'Tal Vez', options: ['Tal Vez', 'Quizás', 'Probablemente', 'Definitivamente'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '5Eax0qFko2dh7Rl2lYs3bx', question: 'What\'s the name of this song?', answer: 'Efecto', options: ['Efecto', 'Me Porto Bonito', 'Callaíta', 'Safaera'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '0tFBa3NqshAkpplNEcQWwR', question: 'Who\'s the author of this song?', answer: 'Sexenni', options: ['Bad Bunny', 'Ozuna', 'Sech', 'Sexenni'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '4ilZV1WNjL7IxwE81OnaRY', question: 'Who\'s the author of this song?', answer: 'Bellakath', options: ['Bellakath', 'Tokisha', 'KAROL G', 'Natti Natasha'] },
  { kind: 'spotify trivia', difficult: true, type: 'spotify', track: '2vsJwShF49IoMVkz5onWPT', question: 'Who\'s the author of this song?', answer: 'Mula', options: ['Mula', 'Camila Cabello', 'Karol G', 'Rosalía'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '4kXxEhuatrvwrTQycA7s9B', question: 'What\'s the name of this song?', answer: 'Bizcochito', options: ['Bizcochito', 'Dulcecito', 'Galletita', 'Pastelito'] },
  // newer trivias
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '60a0Rd6pjrkxjPbaKzXjfq', question: 'What\'s the name of this song?', answer: 'In the End', options: ['In the End', 'Numb', 'Crawling', 'Faint'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '2nLtzopw4rPReszdYBJU6h', question: 'Who\'s the author of this song?', answer: 'Linkin Park', options: ['Linkin Park', 'Sum 41', 'Foo Fighters', 'System of a Down'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '5IVuqXILoxVWvWEPm82Jxr', question: 'What\'s the name of this song?', answer: 'Crazy In Love', options: ['Crazy In Love', 'We Found Love', 'Can\'t Stop the Feeling!', 'Treasure'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '0DiWol3AO6WpXZgp0goxAV', question: 'Who\'s the author of this song?', answer: 'Daft Punk', options: ['Daft Punk', 'Gorillaz', 'The Prodigy', 'ODESZA'] },
  { kind: 'spotify trivia', difficult: true, type: 'spotify', track: '0Ph6L4l8dYUuXFmb71Ajnd', question: 'Who\'s the author of this song?', answer: 'Ricky Martin', options: ['Ricky Martin', 'Carlos Vives', 'Marc Anthony', 'Romeo Santos'] },
  { kind: 'spotify trivia', difficult: true, type: 'spotify', track: '1ixbwbeBi5ufN4noUKmW5a', question: 'What\'s the name of this song?', answer: 'Paper Planes', options: ['Paper Planes', 'Bad Girls', 'Disparate Youth', 'Lean On'] },
  { kind: 'spotify trivia', difficult: true, type: 'spotify', track: '6RX5iL93VZ5fKmyvNXvF1r', question: 'What\'s the name of this song?', answer: 'Irreplaceable', options: ['Irreplaceable', 'If I Ain\'t Got You', 'Survivor', 'Be Without You'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '0gmbgwZ8iqyMPmXefof8Yf', question: 'Who\'s the author of this song?', answer: 'Nickelback', options: ['Nickelback', '3 Doors Down', 'Sum 41', 'Theory of a Deadman'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '0JiY190vktuhSGN6aqJdrt', question: 'Who\'s the author of this song?', answer: 'P!nk', options: ['P!nk', 'Katy Perry', 'Demi Lovato', 'Kesha'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '6I9VzXrHxO9rA9A5euc8Ak', question: 'Who\'s the author of this song?', answer: 'Britney Spears', options: ['Britney Spears', 'Beyoncé', 'Selena Gomez', 'Christina Aguilera'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '4fixebDZAVToLbUCuEloa2', question: 'Who\'s the author of this song?', answer: 'Britney Spears', options: ['Britney Spears', 'Beyoncé', 'Selena Gomez', 'Christina Aguilera'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '6naxalmIoLFWR0siv8dnQQ', question: 'What\'s the name of this song?', answer: 'Oops!...I Did It Again', options: ['Oops!...I Did It Again', 'Oh! I\'m at It Again', 'Oops', 'Didn`t do it again'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '5R9a4t5t5O0IsznsrKPVro', question: 'Who\'s the author of this song?', answer: 'Beyoncé', options: ['Beyoncé', 'Britney Spears', 'Selena Gomez', 'Christina Aguilera'] },
  { kind: 'spotify trivia', difficult: true, type: 'spotify', track: '5s4catxeZsaWFnOrvrXZHf', question: 'What\'s the name of this song?', answer: 'That\'s the Way It Is', options: ['That\'s the Way It Is', 'Greatest Love of All', 'Hero', 'How Do I Live'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '6LefIBy3hzTN6Yd1m81gpC', question: 'Who\'s the author of this song?', answer: 'Céline Dion', options: ['Céline Dion', 'Mariah Carey', 'Adele', 'Lara Fabian'] },
  { kind: 'spotify trivia', difficult: true, type: 'spotify', track: '5fdNHVZHbWB1AaXk4RBGVD', question: 'Who\'s the author of this song?', answer: 'Grover Washington, Jr.', options: ['Grover Washington, Jr.', 'David Sanborn', 'George Benson', 'Richard Elliot'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '5knuzwU65gJK7IF5yJsuaW', question: 'What\'s the name of this song?', answer: 'Rockabye', options: ['Rockabye', 'Lean On', 'Let Me Love You', 'Lush Life'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '2ekn2ttSfGqwhhate0LSR0', question: 'Who\'s the author of this song?', answer: 'Dua Lipa', options: ['Dua Lipa', 'Rita Ora', 'Sia', 'Camila Cabello'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '386RUes7n1uM1yfzgeUuwp', question: 'What\'s the name of this song?', answer: 'The Lazy Song', options: ['The Lazy Song', 'Happy', 'Naive', 'Sleep'] },
  { kind: 'spotify trivia', difficult: true, type: 'spotify', track: '1rfofaqEpACxVEHIZBJe6W', question: 'Who\'s the author of this song?', answer: 'Camila Cabello', options: ['Camila Cabello', 'Selena Gomez', 'Demi Lovato', 'Hailee Steinfeld'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '6JV2JOEocMgcZxYSZelKcc', question: 'Who\'s the author of this song?', answer: 'Justin Timberlake', options: ['Justin Timberlake', 'Bruno Mars', 'Chris Brown', 'Pharrell Williams'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '3tgZ9vmhuAY9wEoNUJskzV', question: 'Who\'s the author of this song?', answer: 'Pitbull', options: ['Flo Rida', 'Sean Paul', 'David Guetta', 'Pitbull'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '1rqqCSm0Qe4I9rUvWncaom', question: 'Who\'s the author of this song?', answer: 'Panic! At The Disco', options: ['Panic! At The Disco', 'Fall Out Boy', 'Twenty One Pilots', 'The Killers'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '5Fla3zyOCcIRqrDoKLU0DP', question: 'Who\'s the author of this song?', answer: 'Rita Ora', options: ['Rita Ora', 'Dua Lipa', 'Bebe Rexha', 'Anne-Marie'] },
  { kind: 'spotify trivia', difficult: false, type: 'spotify', track: '4lJNen4SMTIJMahALc3DcB', question: 'Who are the authors of this song?', answer: 'Sia, Diplo, Labrinth', options: ['Sia, Diplo, Labrinth', 'Sia, Major Lazer, Flume', 'Sia, Labrinth, Galantis, Tove Lo', 'Sia, LSD, Major Lazer'] },

  { kind: 'trivia', difficult: false, type: 'trivia', question: 'What is the capital city of Japan?', answer: 'Tokyo', options: ['Tokyo', 'Beijing', 'Seoul', 'Bangkok'] },
  { kind: 'trivia', difficult: false, type: 'trivia', question: 'Which famous scientist formulated the theory of relativity, E=mc^2?', answer: 'Albert Einstein', options: ['Isaac Newton', 'Albert Einstein', 'Galileo Galilei', 'Nikola Tesla'] },
  { kind: 'trivia', difficult: false, type: 'trivia', question: 'Who painted the famous artwork "Mona Lisa"?', answer: 'Leonardo da Vinci', options: ['Leonardo da Vinci', 'Vincent van Gogh', 'Pablo Picasso', 'Michelangelo'] },
  { kind: 'trivia', difficult: false, type: 'trivia', question: 'Which planet is the closest to the Sun?', answer: 'Mercury', options: ['Mercury', 'Venus', 'Earth', 'Pluto'] },
  { kind: 'trivia', difficult: false, type: 'trivia', question: 'Which famous scientist is credited with discovering the law of gravity?', answer: 'Isaac Newton', options: ['Albert Einstein', 'Isaac Newton', 'Marie Curie', 'Charles Darwin'] },
  { kind: 'trivia', difficult: false, type: 'trivia', question: 'What is the largest organ in the human body?', answer: 'Skin', options: ['Liver', 'Skin', 'Heart', 'Lungs'] },
  { kind: 'trivia', difficult: false, type: 'trivia', question: 'In Greek mythology, who is the king of the gods?', answer: 'Zeus', options: ['Apollo', 'Zeus', 'Poseidon', 'Hermes'] },
  { kind: 'trivia', difficult: false, type: 'trivia', question: 'Which country is known as the "Land of the Rising Sun"?', answer: 'Japan', options: ['China', 'Japan', 'South Korea', 'Vietnam'] },
  { kind: 'trivia', difficult: false, type: 'trivia', question: 'What is the chemical symbol for gold?', answer: 'Au', options: ['Au', 'Go', 'Gd', 'Gr'] },
  { kind: 'trivia', difficult: false, type: 'trivia', question: 'What is the largest ocean on Earth?', answer: 'Pacific Ocean', options: ['Indian Ocean', 'Atlantic Ocean', 'Arctic Ocean', 'Pacific Ocean'] },
  { kind: 'trivia', difficult: false, type: 'trivia', question: 'What is the main gas that makes up the Earth\'s atmosphere?', answer: 'Nitrogen (N2)', options: ['Oxygen (O2)', 'Carbon dioxide (CO2)', 'Nitrogen (N2)', 'Argon (Ar)'] },
  { kind: 'trivia', difficult: false, type: 'trivia', question: 'What is the chemical symbol for the element iron?', answer: 'Fe', options: ['Ir', 'Fe', 'Io', 'In'] },
  { kind: 'trivia', difficult: false, type: 'trivia', question: 'What is the tallest mountain in the world?', answer: 'Mount Everest', options: ['Mount Kilimanjaro', 'Mount Everest', 'Mount McKinley (Denali)', 'Mount Fuji'] },
  { kind: 'trivia', difficult: true, type: 'trivia', question: 'What is the currency of Switzerland?', answer: 'Swiss Franc', options: ['Swiss Franc', 'Pound Sterling', 'Euro', 'Yen'] },
  { kind: 'trivia', difficult: false, type: 'trivia', question: 'What is the name of the world\'s largest desert?', answer: 'Sahara Desert', options: ['Sahara Desert', 'Arabian Desert', 'Gobi Desert', 'Kalahari Desert'] },
  { kind: 'trivia', difficult: false, type: 'trivia', question: 'What is the name of the world\'s largest river by volume?', answer: 'Amazon River', options: ['Amazon River', 'Congo River', 'Nile River', 'Dnipro River'] },
  { kind: 'trivia', difficult: false, type: 'trivia', question: 'What is the name of the world\'s largest island?', answer: 'Greenland', options: ['Greenland', 'New Guinea', 'Borneo', 'Madagascar'] },
  { kind: 'trivia', difficult: true, type: 'trivia', question: 'Which planet in our solar system has the most moons?', answer: 'Jupiter', options: ['Saturn', 'Mars', 'Jupiter', 'Uranus'] },
  { kind: 'trivia', difficult: false, type: 'trivia', question: 'What is the most spoken language in the world?', answer: 'Mandarin Chinese', options: ['Mandarin Chinese', 'Spanish', 'English', 'Hindi'] },
  { kind: 'trivia', difficult: false, type: 'trivia', question: 'Which river is the longest in the world?', answer: 'Nile River', options: ['Amazon River', 'Nile River', 'Mississippi River', 'Yangtze River'] },
  { kind: 'trivia', difficult: true, type: 'trivia', question: 'Which natural disaster is measured using the Richter scale?', answer: 'Earthquake', options: ['Hurricane', 'Tornado', 'Earthquake', 'Tsunami'] },
  { kind: 'trivia', difficult: true, type: 'trivia', question: 'What is the name of the world\'s largest producer of bananas?', answer: 'Ecuador', options: ['India', 'China', 'Ecuador', 'Brazil'] },
  { kind: 'trivia', difficult: true, type: 'trivia', question: 'What is the name of the world\'s largest producer of oranges?', answer: 'Brazil', options: ['Brazil', 'United States', 'China', 'Spain'] },
  { kind: 'trivia', difficult: false, type: 'trivia', question: 'Which country has the most billionaires?', answer: 'United States', options: ['United States', 'China', 'Germany', 'Japan'] },
  { kind: 'trivia', difficult: false, type: 'trivia', question: 'Which country has the smallest population?', answer: 'Vatican City', options: ['Vatican City', 'Nauru', 'Tuvalu', 'Monaco'] },
  { kind: 'trivia', difficult: true, type: 'trivia', question: 'Which country has the oldest university?', answer: 'Bologna, Italy', options: ['Bologna, Italy', 'Oxford, England', 'Salamanca, Spain', 'Paris, France'] },
  { kind: 'trivia', difficult: false, type: 'trivia', question: 'Which music video, released in 2012, became the most-watched video on YouTube, reaching over 7 billion views?', answer: '"Despacito" by Luis Fonsi and Daddy Yankee', options: ['"Baby" by Justin Bieber', '"Gangnam Style" by PSY', '"Despacito" by Luis Fonsi and Daddy Yankee', '"Shape of You" by Ed Sheeran'] },
  { kind: 'trivia', difficult: false, type: 'trivia', question: 'Which song by Adele became a massive hit in 2015 and won the Grammy Award for Record of the Year?', answer: 'Hello', options: ['Rolling in the Deep', 'Hello', 'Someone Like You', 'Skyfall'] },
  { kind: 'trivia', difficult: false, type: 'trivia', question: 'In the movie "Frozen," what is the name of Elsa\'s sister who sets out on a journey to bring her back to their kingdom?', answer: 'Anna', options: ['Cinderella', 'Rapunzel', 'Anna', 'Belle'] },
  { kind: 'trivia', difficult: false, type: 'trivia', question: '"Zootopia" takes place in a city where animals live together. What kind of animal is the main character, Judy Hopps?', answer: 'Rabbit', options: ['Rabbit', 'Fox', 'Lion', 'Elephant'] },
  { kind: 'trivia', difficult: false, type: 'trivia', question: 'What was the first soft drink in space?', answer: 'Coca-Cola', options: ['Coca-Cola', 'Pepsi', 'Sprite', 'Fanta'] },
  { kind: 'trivia', difficult: false, type: 'trivia', question: 'Which country consumes the most chocolate per capita?', answer: 'Switzerland', options: ['Switzerland', 'Belgium', 'Germany', 'Netherlands'] },
  { kind: 'trivia', difficult: false, type: 'trivia', question: 'What is the most consumed manufactured drink in the world?', answer: 'Tea', options: ['Tea', 'Juice', 'Soda', 'Coffee'] },
  { kind: 'trivia', difficult: true, type: 'trivia', question: 'Which country invented ice cream?', answer: 'China', options: ['China', 'Italy', 'France', 'Greece'] },
  { kind: 'trivia', difficult: false, type: 'trivia', question: 'Which one is not one of the 7 wonders?', answer: 'Petra', options: ['The Colosseum', 'The Great Wall of China', 'Chichén Itzá', 'Petra'] },
  { kind: 'trivia', difficult: true, type: 'trivia', question: 'What company was originally called "Cadabra"?', answer: 'Amazon', options: ['Amazon', 'Walmart', 'eBay', 'Alibaba'] },
  { kind: 'trivia', difficult: false, type: 'trivia', question: 'What is the national dish of Spain?', answer: 'Paella', options: ['Paella', 'Tapas', 'Tortilla Española', 'Gazpacho'] },
  { kind: 'trivia', difficult: true, type: 'trivia', question: 'What is the stage name of Stefani Joanne Angelina Germanotta?', answer: 'Lady Gaga', options: ['Lady Gaga', 'Madonna', 'Katy Perry', 'Rihanna'] },
  { kind: 'trivia', difficult: true, type: 'trivia', question: 'How many members does BTS have?', answer: '7', options: ['7', '6', '5', '9'] },
  { kind: 'trivia', difficult: false, type: 'trivia', question: 'What is the highest-grossing movie of all time?', answer: 'Avatar', options: ['Avatar', 'Avengers: Endgame', 'Titanic', 'Star Wars: The Force Awakens'] },
  
  { kind: 'image trivia', difficult: false, type: 'trivia', question: 'Who painted the famous artwork "Starry Night"?', answer: 'Vincent van Gogh', options: ['Vincent van Gogh', 'Pablo Picasso', 'Marie Curie', 'Michelangelo'], image: '/tileimages/starrynight.jpg' },
  { kind: 'image trivia', difficult: false, type: 'trivia', question: 'In which country can you find the ancient ruins of Machu Picchu?', answer: 'Peru', options: ['Peru', 'Mexico', 'Chile', 'Brazil'], image: '/tileimages/Machu_Picchu.jpg' },
  { kind: 'image trivia', difficult: true, type: 'trivia', question: 'Where did the band ABBA form?', answer: 'Sweden', options: ['Sweden', 'United States', 'United Kingdom', 'Norway'], image: '/tileimages/abba.jpg' },
  { kind: 'image trivia', difficult: true, type: 'trivia', question: 'Where is Acropolis located?', answer: 'Greece', options: ['Greece', 'Italy', 'Spain', 'Peru'], image: '/tileimages/acropolis.jpg' },
  { kind: 'image trivia', difficult: false, type: 'trivia', question: 'Where is this landmark located?', answer: 'Spain', options: ['Spain', 'France', 'Italy', 'Portugal'], image: '/tileimages/landmark1.jpg' },
  { kind: 'image trivia', difficult: false, type: 'trivia', question: 'Where is this building located?', answer: 'USA', options: ['USA', 'Canada', 'United Kingdom', 'Germany'], image: '/tileimages/Empire_State_Building_(aerial_view).jpg' },
  { kind: 'image trivia', difficult: true, type: 'trivia', question: 'Where is Uluru located?', answer: 'Australia', options: ['Australia', 'New Zealand', 'Brazil', 'Argentina'], image: '/tileimages/ULURU.jpg' },
  { kind: 'image trivia', difficult: true, type: 'trivia', question: 'Where is this landmark located?', answer: 'France', options: ['France', 'Italy', 'Spain', 'Belgium'], image: '/tileimages/saint_michele.jpg' },
  { kind: 'image trivia', difficult: true, type: 'trivia', question: 'Where is Mount Kilimanjaro located?', answer: 'Tanzania', options: ['Tanzania', 'Kenya', 'Uganda', 'Ethiopia'], image: '/tileimages/kilimanjaro.jpg' },
  { kind: 'image trivia', difficult: false, type: 'trivia', question: 'Where is Chichen Itza located?', answer: 'Mexico', options: ['Mexico', 'Peru', 'Guatemala', 'El Salvador'], image: '/tileimages/chichen-itza-pyramid-equinox.jpg' },
  { kind: 'image trivia', difficult: true, type: 'trivia', question: 'Where is Victoria Falls located?', answer: 'Zambia', options: ['Zambia', 'Zimbabwe', 'Tanzania', 'South Africa'], image: '/tileimages/victorian_waterfalls.jpg' },
  { kind: 'image trivia', difficult: false, type: 'trivia', question: 'Where is Alhambra located?', answer: 'Spain', options: ['Spain', 'Portugal', 'Morocco', 'Turkey'], image: '/tileimages/Alhambra-Fortress-Granada-Spain-700-x-425.jpg' },
  { kind: 'image trivia', difficult: true, type: 'trivia', question: 'Where is Hạ Long Bay located?', answer: 'Vietnam', options: ['Vietnam', 'Thailand', 'Cambodia', 'Malaysia'], image: '/tileimages/halongbay.jpg' },
  { kind: 'image trivia', difficult: false, type: 'trivia', question: 'Where are the Niagara Falls located?', answer: 'Canada', options: ['Canada', 'USA', 'Mexico', 'Brazil'], image: '/tileimages/niagara_falls.jpg' },
  { kind: 'image trivia', difficult: false, type: 'trivia', question: 'Where is Park Guell located?', answer: 'Barcelona, Spain', options: ['Barcelona, Spain', 'Rome, Italy', 'Lisbon, Portugal', 'Vienna, Austria'], image: '/tileimages/antoni-gaudi-spain-barcelona-Parc-Guell-05-samuel-ludwig.jpg' },
  { kind: 'image trivia', difficult: true, type: 'trivia', question: 'Where is Belem Tower located?', answer: 'Lisbon, Portugal', options: ['Lisbon, Portugal', 'Madrid, Spain', 'Rome, Italy', 'Athens, Greece'], image: '/tileimages/Torre_Belem_April_2009-4a.jpg' },
  { kind: 'image trivia', difficult: true, type: 'trivia', question: 'Where is this building located, which is also know as Walkie Talkie?', answer: 'London', options: ['London', 'New York City', 'Dubai', 'Tokyo'], image: '/tileimages/Walkie-Talkie_-_Sept_2015.jpg' },
  { kind: 'image trivia', difficult: false, type: 'trivia', question: 'Where is this tower located?', answer: 'Dubai, UAE', options: ['Dubai, UAE', 'Doha, Qatar', 'Riyadh, Saudi Arabia', 'Kuwait City, Kuwait'], image: '/tileimages/burj_khalifa.jpg' },
  
  { kind: 'image trivia', difficult: true, type: 'trivia', question: 'This is a macro photo of...', answer: 'Pear', options: ['Pear', 'Sponge', 'Microorganism', 'Wood'], image: '/tileimages/Video-shows-everyday-objects-through-a-macro-lens-5e8197ea26e4f-png__880.jpg' },
  { kind: 'image trivia', difficult: true, type: 'trivia', question: 'This is a macro photo of...', answer: 'Soap', options: ['Soap', 'Candle', 'Lotion', 'Clay'], image: '/tileimages/Video-shows-everyday-objects-through-a-macro-lens-5e8197fe8cb30-png__880.jpg' },
  { kind: 'image trivia', difficult: true, type: 'trivia', question: 'This is a macro photo of...', answer: 'Toilet paper', options: ['Toilet paper', 'Tissues', 'Gift Wrap', 'Sponge'], image: '/tileimages/Video-shows-everyday-objects-through-a-macro-lens-5e8198185a92f-png__880.jpg' },
  { kind: 'image trivia', difficult: true, type: 'trivia', question: 'This is a macro photo of...', answer: 'Cinnamon', options: ['Cinnamon', 'Wood', 'Pine', 'Paintbrush'], image: '/tileimages/ezgif-1-0a1b8ee2bb.jpg' },
  
  { kind: 'truth or dare', difficult: false, type: 'dareortruth', truth: 'Would you kill a person if you needed food?', dare: 'Bite a table!' },
  { kind: 'truth or dare', difficult: false, type: 'dareortruth', truth: 'Have you ever cheated on a test or exam?', dare: 'Do your best impression of a famous celebrity' },
  { kind: 'truth or dare', difficult: false, type: 'dareortruth', truth: 'What is your most embarrassing nickname?', dare: 'Say in a foreign accent "I love you {2}"' },
  { kind: 'truth or dare', difficult: false, type: 'dareortruth', truth: 'Have you ever been caught picking your nose?', dare: 'Go outside and yell "I love ice cream"' },
  { kind: 'truth or dare', difficult: false, type: 'dareortruth', truth: 'What is the weirdest dream you\'ve ever had?', dare: 'Call a random number wish them Happy Birthday' },
  { kind: 'truth or dare', difficult: false, type: 'dareortruth', truth: 'Have you ever had a crush on a teacher?', dare: 'Dance like a chicken' },
  { kind: 'truth or dare', difficult: false, type: 'dareortruth', truth: 'What is the most childish thing you still do?', dare: 'Try to lick your elbow' },
  { kind: 'truth or dare', difficult: false, type: 'dareortruth', truth: 'Have you ever snooped through someone else\'s phone or belongings?', dare: 'Do a cartwheel' },
  { kind: 'truth or dare', difficult: false, type: 'dareortruth', truth: 'What is one thing you regret doing or not doing?', dare: 'Kiss the nearest person to you' },
  { kind: 'truth or dare', difficult: false, type: 'dareortruth', truth: 'What was the first gift {2} gifted you and what for?', dare: 'Lick the floor' },
  { kind: 'truth or dare', difficult: false, type: 'dareortruth', truth: 'What is the most embarrassing thing your parents have caught you doing?', dare: 'Go to the nearest store and buy something ridiculous' },
  { kind: 'truth or dare', difficult: false, type: 'dareortruth', truth: 'Have you ever pretended to be sick to avoid something or someone?', dare: 'Spin around 10 times and then try to walk in a straight line' },
  { kind: 'truth or dare', difficult: false, type: 'dareortruth', truth: 'What is the silliest lie you\'ve ever told that people actually believed?', dare: 'Call a local store and ask if they sell unicorn food' },
  { kind: 'truth or dare', difficult: false, type: 'dareortruth', truth: 'What is the most trouble you\'ve ever gotten into at school?', dare: 'Text your best friend with your nose only, without explaining why' },
  { kind: 'truth or dare', difficult: false, type: 'dareortruth', truth: 'Have you ever eavesdropped on someone\'s conversation unintentionally?', dare: 'Balance a spoon on your nose for as long as you can' },
  { kind: 'truth or dare', difficult: true, type: 'dareortruth', truth: 'What is one thing you wish you could change about yourself?', dare: 'Do an interpretative dance to your favorite song' },
  { kind: 'truth or dare', difficult: true, type: 'dareortruth', truth: 'Have you ever had a crush on a cartoon or fictional character? Who?', dare: 'Do 20 sit-ups' },
  { kind: 'truth or dare', difficult: true, type: 'dareortruth', truth: 'What is your most embarrassing childhood memory?', dare: 'Make a run through every room of the apartment you\'re in' },
  { kind: 'truth or dare', difficult: true, type: 'dareortruth', truth: 'Have you ever been caught talking to yourself?', dare: 'Wear your clothes backward for the next three rounds' },
  { kind: 'truth or dare', difficult: true, type: 'dareortruth', truth: 'What is the strangest thing you\'ve ever eaten?', dare: 'Text your sibling or closest friend and tell them you\'ve joined the circus as a clown' },
  { kind: 'truth or dare', difficult: true, type: 'dareortruth', truth: 'What is your favorite curse word?', dare: 'Do your best "robot dance" for one minute' },
  { kind: 'truth or dare', difficult: true, type: 'dareortruth', truth: 'What do you like about your body?', dare: 'Drink as much water as possible in one go' },
  
  { kind: 'truth or dare', difficult: true, horny: true, type: 'dareortruth', truth: 'Would you let {2} fuck you in the ass?', dare: 'Bite {2}\'s dick!' },
  { kind: 'truth or dare', difficult: true, horny: true, type: 'dareortruth', truth: 'Describe how specifically you would like your clitor to be licked', dare: 'Do a naked dance' },
  { kind: 'truth or dare', difficult: true, horny: true, type: 'dareortruth', truth: 'Talk about compliments you like', dare: 'Lick {2}\'s ear' },
  { kind: 'truth or dare', difficult: true, horny: true, type: 'dareortruth', truth: 'Tell about when you first heard about porn', dare: 'Let {2} buttslap you' },
  { kind: 'image trivia', difficult: false, horny: true, type: 'trivia', question: 'This is the photo of famous porn actor called...', answer: 'Johnny Sins', options: ['Johnny Sins', 'James Deen', 'Ron Jeremy', 'Evan Stone'], image: '/tileimages/artworks-05weslCSgT0srZgR-9gUdXg-t500x500.jpg' },
  { kind: 'image trivia', difficult: false, horny: true, type: 'trivia', question: 'This is the photo of famous porn actress called...', answer: 'Sasha Grey', options: ['Sasha Grey', 'Lana Rhoades', 'Mia Malkova', 'Mia Khalifa'], image: '/tileimages/41Qn3jBM5eL._AC_UF894,1000_QL80_.jpg' },
  { kind: 'image trivia', difficult: true, horny: true, type: 'trivia', question: 'This is the photo of famous porn actress called...', answer: 'Mia Malkova', options: ['Mia Malkova', 'Sasha Grey', 'Lana Rhoades', 'Mia Khalifa'], image: '/tileimages/16575396203051.jpg' },
  { kind: 'image trivia', difficult: true, horny: true, type: 'trivia', question: 'Largest breasts in the world weight...', answer: '40kg', options: ['50kg', '10kg', '20kg', '40kg'], image: '/tileimages/120718021357-drew-woman-largest-natural-breasts-00011603.jpg' },
  { kind: 'trivia', difficult: true, horny: true, type: 'trivia', question: 'How long can sperm survive for in best-case scenario?', answer: 'Up to 5 days', options: ['Up to 5 days', '3 days', '1 minute', '3 minutes'] },
  { kind: 'poll', difficult: false, horny: true, type: 'poll', question: 'Which is better?', options: ['Ass', 'Tits'] },
  { kind: 'poll', difficult: true, horny: true, type: 'poll', question: 'Which is worse?', options: ['Tits on a guy', 'Vagina on a guy'] },
  { kind: 'poll', difficult: false, horny: true, type: 'poll', question: 'Which is better?', options: ['Blowjob', 'Cunnilingus'] },
  { kind: 'poll', difficult: false, horny: true, type: 'poll', question: 'Which is better?', options: ['Handjob', 'Footjob'] },
  { kind: 'poll', difficult: false, horny: true, type: 'poll', question: 'Would you rather?', options: ['Fuck a paid hooker', 'Fuck with a random guy on Tinder'] },
  
  { kind: 'poll', difficult: false, type: 'poll', question: 'Which is less bad?', options: ['"Shape of You" by Ed Sheeran', '"Despacito" by Luis Fonsi & Daddy Yankee'] },
  { kind: 'poll', difficult: false, type: 'poll', question: 'Which is better?', options: ['"Happy" by Pharrell Williams', '"Uptown Funk" by Mark Ronson ft. Bruno Mars'] },
  { kind: 'poll', difficult: false, type: 'poll', question: 'Which is less bad?', options: ['Billie Eilish', 'Justin Bieber'] },
  { kind: 'poll', difficult: false, type: 'poll', question: 'Which is better?', options: ['Oranges', 'Mandarin'] },
  { kind: 'poll', difficult: false, type: 'poll', question: 'Which is better?', options: ['Pear', 'Apple'] },
  { kind: 'poll', difficult: false, type: 'poll', question: 'Which is better?', options: ['Cola', 'Fanta'] },
  { kind: 'poll', difficult: false, type: 'poll', question: 'Which is better?', options: ['Champagne', 'Wine'] },
  { kind: 'poll', difficult: false, type: 'poll', question: 'Which is better?', options: ['Dogs', 'Cats'] },
  { kind: 'poll', difficult: false, type: 'poll', question: 'Which is better?', options: ['Sunrise', 'Sunset'] },
  { kind: 'poll', difficult: false, type: 'poll', question: 'Which is better?', options: ['Beach', 'Mountains'] },
  { kind: 'poll', difficult: false, type: 'poll', question: 'Which is better?', options: ['Cake', 'Ice Cream'] },
  { kind: 'poll', difficult: false, type: 'poll', question: 'Which is better?', options: ['Biking', 'Hiking'] },
  { kind: 'poll', difficult: false, type: 'poll', question: 'Which is better?', options: ['Comedy', 'Drama'] },
  { kind: 'poll', difficult: false, type: 'poll', question: 'Which is better?', options: ['Pen', 'Pencil'] },
  { kind: 'poll', difficult: false, type: 'poll', question: 'Which is worse?', options: ['Traffic Jams', 'Long Checkout Lines'] },
  { kind: 'poll', difficult: false, type: 'poll', question: 'Which is better?', options: ['Getting caught in the rain without an umbrella', 'Stepping in a puddle with new shoes'] },
  { kind: 'poll', difficult: false, type: 'poll', question: 'Which is better?', options: ['Working hard', 'Hardly working'] },
  { kind: 'poll', difficult: false, type: 'poll', question: 'Which is better?', options: ['Robots', 'Dinosaurs'] },
];

let current_run: any[];
export const setupTiles = () => {
  current_run = [...tasks];
}

export const getRandomTile = (kind: string|undefined, isDifficult: boolean, isWild: boolean, isHorny: boolean) => {
  const filtered = current_run.filter(a => (isHorny ? true : a.horny !== true) &&
                                           (kind ? a.kind === kind : true));
  // none tiles found
  if (!filtered.length) return {type: null};
  // filter with difficulty
  const filteredWithDifficulty = filtered.filter(a => a.difficult === isDifficult);

  const index = getRandomInt(0, filteredWithDifficulty.length || filtered.length);
  const [value] = current_run.splice(current_run.indexOf((filteredWithDifficulty.length ? filteredWithDifficulty : filtered)[index]), 1);

  return {...value, wild: isWild};
}

export const getRandomAnyTile = (isDifficult: boolean, isHorny: boolean, isDifficultConfig: boolean) => {
  const difficult = isDifficult || randomizeWithThreshold(isDifficultConfig);
  return getRandomTile(undefined, difficult, true, isHorny);
}

export const getRandomKindTile = (kind: string, isDifficult: boolean, isHorny: boolean, isDifficultConfig: boolean) => {
  const difficult = isDifficult || randomizeWithThreshold(isDifficultConfig);
  return getRandomTile(kind, difficult, false, isHorny);
}

export function getRandomInt(min: number, max: number) {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min) + min); // The maximum is exclusive and the minimum is inclusive
}

function randomizeWithThreshold(isDifficultConfig: boolean) {
  let threshold = isDifficultConfig ? 0.7 : 0.3;
  let diff = Math.random() > threshold ? true : false;
  return diff;
}