import '@/app/globals.css'
import { Inter, Concert_One, Montserrat } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const concert_one = Concert_One({
  subsets: ['latin'],
  display: 'swap',
  weight: "400",
  variable: '--font-concert-one'
});

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  weight: "400",
  variable: '--font-montserrat'
});

export const metadata = {
  title: 'Tile Game',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${concert_one.variable} ${montserrat.variable}`}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
